import{a as S,S as w,i as a}from"./assets/vendor-frHSA4Lh.js";(function(){const r=document.createElement("link").relList;if(r&&r.supports&&r.supports("modulepreload"))return;for(const e of document.querySelectorAll('link[rel="modulepreload"]'))c(e);new MutationObserver(e=>{for(const n of e)if(n.type==="childList")for(const l of n.addedNodes)l.tagName==="LINK"&&l.rel==="modulepreload"&&c(l)}).observe(document,{childList:!0,subtree:!0});function o(e){const n={};return e.integrity&&(n.integrity=e.integrity),e.referrerPolicy&&(n.referrerPolicy=e.referrerPolicy),e.crossOrigin==="use-credentials"?n.credentials="include":e.crossOrigin==="anonymous"?n.credentials="omit":n.credentials="same-origin",n}function c(e){if(e.ep)return;e.ep=!0;const n=o(e);fetch(e.href,n)}})();const q="https://pixabay.com/api/",v="50191588-7d0b750c5d17d1451aa626dbf";async function f(t,r=1){try{return(await S.get(q,{params:{key:v,q:t,image_type:"photo",orientation:"horizontal",safesearch:!0,page:r,per_page:15}})).data}catch(o){throw new Error(`Failed to fetch images: ${o.message}`)}}const B=new w(".gallery a",{captionsData:"alt",captionDelay:250});function m(t){const r=document.querySelector(".gallery"),o=t.map(({webformatURL:c,largeImageURL:e,tags:n,likes:l,views:p,comments:b,downloads:L})=>`
        <li class="gallery-item">
          <a href="${e}">
            <img src="${c}" alt="${n}" />
          </a>
          <div class="info">
            <p><b>Likes:</b> ${l}</p>
            <p><b>Views:</b> ${p}</p>
            <p><b>Comments:</b> ${b}</p>
            <p><b>Downloads:</b> ${L}</p>
          </div>
        </li>
      `).join("");r.insertAdjacentHTML("beforeend",o),B.refresh()}function E(){const t=document.querySelector(".gallery");t.innerHTML=""}function y(){document.querySelector(".loader").classList.remove("hidden")}function g(){document.querySelector(".loader").classList.add("hidden")}function M(){document.querySelector(".load-more").classList.remove("hidden")}function d(){document.querySelector(".load-more").classList.add("hidden")}const h=document.querySelector(".form"),P=h.querySelector("[name='search-text']"),R=document.querySelector(".load-more");let u="",s=1,i=0;h.addEventListener("submit",$);R.addEventListener("click",O);async function $(t){t.preventDefault();const r=P.value.trim();if(!r){a.error({title:"Error",message:"Please enter a search query",position:"topRight"});return}u=r,s=1,i=0,d(),y(),E();try{const o=await f(u,s);i=o.totalHits,o.hits.length===0?a.error({title:"No Results",message:"Sorry, there are no images matching your search query. Please try again!",position:"topRight"}):(m(o.hits),o.hits.length<15||s*15>=i?(d(),s*15>=i&&a.info({title:"End of Results",message:"We're sorry, but you've reached the end of search results.",position:"topRight"})):M())}catch{a.error({title:"Error",message:"Something went wrong. Please try again later.",position:"topRight"})}finally{g(),h.reset()}}async function O(){s+=1,y();try{const t=await f(u,s);m(t.hits);const r=document.querySelector(".gallery-item");if(r){const{height:o}=r.getBoundingClientRect();window.scrollBy({top:o*2,behavior:"smooth"})}(t.hits.length<15||s*15>=i)&&(d(),s*15>=i&&a.info({title:"End of Results",message:"We're sorry, but you've reached the end of search results.",position:"topRight"}))}catch{a.error({title:"Error",message:"Something went wrong. Please try again later.",position:"topRight"})}finally{g()}}
//# sourceMappingURL=index.js.map
